# Updates a Formula
# Triggers on Repository Dispatch
# Hosts the Formula on github-actions and on master

on: 
  repository_dispatch: # https://github.com/peter-evans/repository-dispatch#readme
    types: [version-update]
  workflow_dispatch:

env: 
  packageName: "@useoptic/cli"
  exportName: api # must be capitalized since ruby classes are capitalized
  cleanedPkgName: useopticcli # just remove all special characters and make lowercase (no @s or /s)

jobs:
  # I don't believe anything here requires MacOS (go-task has other installation options) and this could be
  # converted later to another runner if desired.
  update-formula:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: brew install go-task/tap/go-task
      - run: task build # Build includes a local commit to run test, and we can push in the next step
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main